version: "3.3"
services:
  client:
    container_name: my_client
    build: ./client/
    tty: true
    stdin_open: true


  worker:
    container_name: my_worker
    build: ./worker/
    tty: true
    stdin_open: true


  redis_server:
    container_name: my_redis
    image: redis:alpine
    restart: always
    ports:
        - '127.0.0.1:6379:6379'
    healthcheck:
      test: curl -sS http://127.0.0.1 || echo 1
      interval: 5s
      timeout: 10s
      retries: 3



